/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthU2fRouteImport } from './routes/auth/u2f'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthRecoveryRouteImport } from './routes/auth/recovery'
import { Route as AuthOtpRouteImport } from './routes/auth/otp'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotRouteImport } from './routes/auth/forgot'
import { Route as AuthActivationRouteImport } from './routes/auth/activation'
import { Route as Auth2faRouteImport } from './routes/auth/2fa'
import { Route as AppMeRouteRouteImport } from './routes/_app/me/route'
import { Route as AppMeIndexRouteImport } from './routes/_app/me/index'
import { Route as AppMeSettingsRouteImport } from './routes/_app/me/settings'
import { Route as AppMeSecurityRouteImport } from './routes/_app/me/security'
import { Route as AppMeLogsRouteImport } from './routes/_app/me/logs'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthU2fRoute = AuthU2fRouteImport.update({
  id: '/u2f',
  path: '/u2f',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRecoveryRoute = AuthRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthActivationRoute = AuthActivationRouteImport.update({
  id: '/activation',
  path: '/activation',
  getParentRoute: () => AuthRouteRoute,
} as any)
const Auth2faRoute = Auth2faRouteImport.update({
  id: '/2fa',
  path: '/2fa',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppMeRouteRoute = AppMeRouteRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppMeIndexRoute = AppMeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMeRouteRoute,
} as any)
const AppMeSettingsRoute = AppMeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppMeRouteRoute,
} as any)
const AppMeSecurityRoute = AppMeSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppMeRouteRoute,
} as any)
const AppMeLogsRoute = AppMeLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppMeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/': typeof AppIndexRoute
  '/terms': typeof TermsRoute
  '/me': typeof AppMeRouteRouteWithChildren
  '/auth/2fa': typeof Auth2faRoute
  '/auth/activation': typeof AuthActivationRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/u2f': typeof AuthU2fRoute
  '/me/logs': typeof AppMeLogsRoute
  '/me/security': typeof AppMeSecurityRoute
  '/me/settings': typeof AppMeSettingsRoute
  '/me/': typeof AppMeIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/terms': typeof TermsRoute
  '/auth/2fa': typeof Auth2faRoute
  '/auth/activation': typeof AuthActivationRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/u2f': typeof AuthU2fRoute
  '/': typeof AppIndexRoute
  '/me/logs': typeof AppMeLogsRoute
  '/me/security': typeof AppMeSecurityRoute
  '/me/settings': typeof AppMeSettingsRoute
  '/me': typeof AppMeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRouteRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/terms': typeof TermsRoute
  '/_app/me': typeof AppMeRouteRouteWithChildren
  '/auth/2fa': typeof Auth2faRoute
  '/auth/activation': typeof AuthActivationRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/u2f': typeof AuthU2fRoute
  '/_app/': typeof AppIndexRoute
  '/_app/me/logs': typeof AppMeLogsRoute
  '/_app/me/security': typeof AppMeSecurityRoute
  '/_app/me/settings': typeof AppMeSettingsRoute
  '/_app/me/': typeof AppMeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/'
    | '/terms'
    | '/me'
    | '/auth/2fa'
    | '/auth/activation'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/recovery'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/u2f'
    | '/me/logs'
    | '/me/security'
    | '/me/settings'
    | '/me/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/terms'
    | '/auth/2fa'
    | '/auth/activation'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/recovery'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/u2f'
    | '/'
    | '/me/logs'
    | '/me/security'
    | '/me/settings'
    | '/me'
  id:
    | '__root__'
    | '/auth'
    | '/_app'
    | '/terms'
    | '/_app/me'
    | '/auth/2fa'
    | '/auth/activation'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/recovery'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/u2f'
    | '/_app/'
    | '/_app/me/logs'
    | '/_app/me/security'
    | '/_app/me/settings'
    | '/_app/me/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/u2f': {
      id: '/auth/u2f'
      path: '/u2f'
      fullPath: '/auth/u2f'
      preLoaderRoute: typeof AuthU2fRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/recovery': {
      id: '/auth/recovery'
      path: '/recovery'
      fullPath: '/auth/recovery'
      preLoaderRoute: typeof AuthRecoveryRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/activation': {
      id: '/auth/activation'
      path: '/activation'
      fullPath: '/auth/activation'
      preLoaderRoute: typeof AuthActivationRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/2fa': {
      id: '/auth/2fa'
      path: '/2fa'
      fullPath: '/auth/2fa'
      preLoaderRoute: typeof Auth2faRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me/': {
      id: '/_app/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof AppMeIndexRouteImport
      parentRoute: typeof AppMeRouteRoute
    }
    '/_app/me/settings': {
      id: '/_app/me/settings'
      path: '/settings'
      fullPath: '/me/settings'
      preLoaderRoute: typeof AppMeSettingsRouteImport
      parentRoute: typeof AppMeRouteRoute
    }
    '/_app/me/security': {
      id: '/_app/me/security'
      path: '/security'
      fullPath: '/me/security'
      preLoaderRoute: typeof AppMeSecurityRouteImport
      parentRoute: typeof AppMeRouteRoute
    }
    '/_app/me/logs': {
      id: '/_app/me/logs'
      path: '/logs'
      fullPath: '/me/logs'
      preLoaderRoute: typeof AppMeLogsRouteImport
      parentRoute: typeof AppMeRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  Auth2faRoute: typeof Auth2faRoute
  AuthActivationRoute: typeof AuthActivationRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthRecoveryRoute: typeof AuthRecoveryRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthU2fRoute: typeof AuthU2fRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  Auth2faRoute: Auth2faRoute,
  AuthActivationRoute: AuthActivationRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthRecoveryRoute: AuthRecoveryRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetRoute: AuthResetRoute,
  AuthU2fRoute: AuthU2fRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AppMeRouteRouteChildren {
  AppMeLogsRoute: typeof AppMeLogsRoute
  AppMeSecurityRoute: typeof AppMeSecurityRoute
  AppMeSettingsRoute: typeof AppMeSettingsRoute
  AppMeIndexRoute: typeof AppMeIndexRoute
}

const AppMeRouteRouteChildren: AppMeRouteRouteChildren = {
  AppMeLogsRoute: AppMeLogsRoute,
  AppMeSecurityRoute: AppMeSecurityRoute,
  AppMeSettingsRoute: AppMeSettingsRoute,
  AppMeIndexRoute: AppMeIndexRoute,
}

const AppMeRouteRouteWithChildren = AppMeRouteRoute._addFileChildren(
  AppMeRouteRouteChildren,
)

interface AppRouteChildren {
  AppMeRouteRoute: typeof AppMeRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMeRouteRoute: AppMeRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
