import { execSync } from "node:child_process";
import { unlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const apiUrl = process.env.VITE_API_URL;

if (!apiUrl) {
  console.error(
    "Error: VITE_API_URL is not set.",
    "\nMake sure .env.local contains VITE_API_URL."
  );
  process.exit(1);
}

// Fetch the OpenAPI spec once
const schemaUrl = `${apiUrl}/openapi.json`;
console.log(`Fetching schema from ${schemaUrl}...`);

const response = await fetch(schemaUrl);
if (!response.ok) {
  console.error(`Failed to fetch OpenAPI schema: ${response.status}`);
  process.exit(1);
}
const openapi = await response.json();

const outDir = "src/api/generated";
const importBase = "@/api/generated";
const typesOutput = join(outDir, "schema.d.ts");
const enumsOutput = join(outDir, "schema.enums.ts");

// Write to a temp file so openapi-typescript reads from disk (no 2nd fetch)
const tmpFile = join(tmpdir(), "openapi-schema.json");
writeFileSync(tmpFile, JSON.stringify(openapi));

// 1. Generate schema.d.ts
execSync(`openapi-typescript "${tmpFile}" -o ${typesOutput}`, {
  stdio: "inherit",
});

unlinkSync(tmpFile);

// 2. Generate schema.enums.ts from the same JSON
const enums = Object.entries(openapi.components?.schemas ?? {})
  .filter(
    ([, schema]) => schema.type === "string" && Array.isArray(schema.enum)
  )
  .sort(([a], [b]) => a.localeCompare(b));

const lines = [
  "/**",
  " * This file was auto-generated by api-sync.",
  " * Do not make direct changes to the file.",
  " */",
  `import type { components } from "${importBase}/schema";`,
  "",
  'type S = components["schemas"];',
  "",
  "export const dtoEnums = {",
];

for (const [name, schema] of enums) {
  const values = schema.enum.map((v) => `"${v}"`).join(", ");
  lines.push(
    `  ${name}: [${values}] as const satisfies readonly S["${name}"][],`
  );
}

lines.push(
  "} as const;",
  "",
  "export type DTOEnumName = keyof typeof dtoEnums;",
  ""
);

writeFileSync(enumsOutput, lines.join("\n"));
console.log(
  `Generated ${typesOutput} + ${enumsOutput} (${enums.length} enums).`
);
