# SPDX-FileCopyrightText: 2026 ChallengeMyProject
#
# SPDX-License-Identifier: AGPL-3.0-only

"""create application route and step route tables

Revision ID: 20260709020000
Revises: 20260709010500
Create Date: 2026-07-09 01:37:52.331579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '20260709020000'
down_revision: Union[str, None] = '20260709010500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_guard',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('header_bearer', 'header_basic', 'header_token', 'query_token', name='application_guard_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='application_guard_status'), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('field_type', sa.Enum('header', 'query', 'post_data', 'raw_data', name='application_guard_field_type'), nullable=False),
    sa.Column('field_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('field_format', sa.Enum('JWT', name='application_guard_field_format'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_guard_account_id'), 'application_guard', ['account_id'], unique=False)
    op.create_index(op.f('ix_application_guard_application_id'), 'application_guard', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_guard_field_type'), 'application_guard', ['field_type'], unique=False)
    op.create_index(op.f('ix_application_guard_owner_id'), 'application_guard', ['owner_id'], unique=False)
    op.create_index(op.f('ix_application_guard_status'), 'application_guard', ['status'], unique=False)
    op.create_index(op.f('ix_application_guard_type'), 'application_guard', ['type'], unique=False)
    op.create_table('application_role',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='application_role_status'), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_role_account_id'), 'application_role', ['account_id'], unique=False)
    op.create_index(op.f('ix_application_role_application_id'), 'application_role', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_role_owner_id'), 'application_role', ['owner_id'], unique=False)
    op.create_index(op.f('ix_application_role_status'), 'application_role', ['status'], unique=False)
    op.create_table('application_route',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('start_application_version_id', sa.Uuid(), nullable=True),
    sa.Column('end_application_version_id', sa.Uuid(), nullable=True),
    sa.Column('application_guard_ids', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('application_role_ids', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='application_route_status'), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('method', sa.Enum('POST', 'GET', 'PATCH', 'PUT', 'DELETE', 'QUERY', name='application_route_method'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accepted_format', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('query_params_schema', sa.JSON(), nullable=False),
    sa.Column('header_schema', sa.JSON(), nullable=False),
    sa.Column('body_schema', sa.JSON(), nullable=False),
    sa.Column('raw_schema', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['end_application_version_id'], ['application_version.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['start_application_version_id'], ['application_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_route_account_id'), 'application_route', ['account_id'], unique=False)
    op.create_index(op.f('ix_application_route_application_id'), 'application_route', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_route_end_application_version_id'), 'application_route', ['end_application_version_id'], unique=False)
    op.create_index(op.f('ix_application_route_method'), 'application_route', ['method'], unique=False)
    op.create_index(op.f('ix_application_route_owner_id'), 'application_route', ['owner_id'], unique=False)
    op.create_index(op.f('ix_application_route_path'), 'application_route', ['path'], unique=False)
    op.create_index(op.f('ix_application_route_start_application_version_id'), 'application_route', ['start_application_version_id'], unique=False)
    op.create_index(op.f('ix_application_route_status'), 'application_route', ['status'], unique=False)
    op.create_table('application_route_response',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('application_route_id', sa.Uuid(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('format', sa.Enum('JSON', 'XML', 'HTML', 'TXT', name='application_route_response_format'), nullable=False),
    sa.Column('body_schema', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['application_route_id'], ['application_route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_route_response_account_id'), 'application_route_response', ['account_id'], unique=False)
    op.create_index(op.f('ix_application_route_response_application_id'), 'application_route_response', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_route_response_application_route_id'), 'application_route_response', ['application_route_id'], unique=False)
    op.create_index(op.f('ix_application_route_response_format'), 'application_route_response', ['format'], unique=False)
    op.create_table('application_route_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('application_route_id', sa.Uuid(), nullable=False),
    sa.Column('database_table_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('query_params', 'query_data', 'query_header', 'response_data', 'response_header', name='application_route_table_type'), nullable=False),
    sa.Column('action', sa.Enum('read', 'create', 'update', 'delete', name='application_route_table_action'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['application_route_id'], ['application_route.id'], ),
    sa.ForeignKeyConstraint(['database_table_id'], ['database_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_route_table_account_id'), 'application_route_table', ['account_id'], unique=False)
    op.create_index(op.f('ix_application_route_table_action'), 'application_route_table', ['action'], unique=False)
    op.create_index(op.f('ix_application_route_table_application_id'), 'application_route_table', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_route_table_application_route_id'), 'application_route_table', ['application_route_id'], unique=False)
    op.create_index(op.f('ix_application_route_table_database_table_id'), 'application_route_table', ['database_table_id'], unique=False)
    op.create_index(op.f('ix_application_route_table_type'), 'application_route_table', ['type'], unique=False)
    op.create_table('journey_scenario_step_route',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('journey_scenario_id', sa.Uuid(), nullable=False),
    sa.Column('journey_scenario_step_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('application_route_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['application_route_id'], ['application_route.id'], ),
    sa.ForeignKeyConstraint(['journey_id'], ['journey.id'], ),
    sa.ForeignKeyConstraint(['journey_scenario_id'], ['journey_scenario.id'], ),
    sa.ForeignKeyConstraint(['journey_scenario_step_id'], ['journey_scenario_step.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_scenario_step_route_account_id'), 'journey_scenario_step_route', ['account_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_step_route_application_id'), 'journey_scenario_step_route', ['application_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_step_route_application_route_id'), 'journey_scenario_step_route', ['application_route_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_step_route_journey_id'), 'journey_scenario_step_route', ['journey_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_step_route_journey_scenario_id'), 'journey_scenario_step_route', ['journey_scenario_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_step_route_journey_scenario_step_id'), 'journey_scenario_step_route', ['journey_scenario_step_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_step_route_owner_id'), 'journey_scenario_step_route', ['owner_id'], unique=False)
    op.create_table('application_route_example',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('application_route_id', sa.Uuid(), nullable=False),
    sa.Column('application_route_response_id', sa.Uuid(), nullable=False),
    sa.Column('query_params', sa.JSON(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['application_route_id'], ['application_route.id'], ),
    sa.ForeignKeyConstraint(['application_route_response_id'], ['application_route_response.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_route_example_account_id'), 'application_route_example', ['account_id'], unique=False)
    op.create_index(op.f('ix_application_route_example_application_id'), 'application_route_example', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_route_example_application_route_id'), 'application_route_example', ['application_route_id'], unique=False)
    op.create_index(op.f('ix_application_route_example_application_route_response_id'), 'application_route_example', ['application_route_response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_route_example_application_route_response_id'), table_name='application_route_example')
    op.drop_index(op.f('ix_application_route_example_application_route_id'), table_name='application_route_example')
    op.drop_index(op.f('ix_application_route_example_application_id'), table_name='application_route_example')
    op.drop_index(op.f('ix_application_route_example_account_id'), table_name='application_route_example')
    op.drop_table('application_route_example')
    op.drop_index(op.f('ix_journey_scenario_step_route_owner_id'), table_name='journey_scenario_step_route')
    op.drop_index(op.f('ix_journey_scenario_step_route_journey_scenario_step_id'), table_name='journey_scenario_step_route')
    op.drop_index(op.f('ix_journey_scenario_step_route_journey_scenario_id'), table_name='journey_scenario_step_route')
    op.drop_index(op.f('ix_journey_scenario_step_route_journey_id'), table_name='journey_scenario_step_route')
    op.drop_index(op.f('ix_journey_scenario_step_route_application_route_id'), table_name='journey_scenario_step_route')
    op.drop_index(op.f('ix_journey_scenario_step_route_application_id'), table_name='journey_scenario_step_route')
    op.drop_index(op.f('ix_journey_scenario_step_route_account_id'), table_name='journey_scenario_step_route')
    op.drop_table('journey_scenario_step_route')
    op.drop_index(op.f('ix_application_route_table_type'), table_name='application_route_table')
    op.drop_index(op.f('ix_application_route_table_database_table_id'), table_name='application_route_table')
    op.drop_index(op.f('ix_application_route_table_application_route_id'), table_name='application_route_table')
    op.drop_index(op.f('ix_application_route_table_application_id'), table_name='application_route_table')
    op.drop_index(op.f('ix_application_route_table_action'), table_name='application_route_table')
    op.drop_index(op.f('ix_application_route_table_account_id'), table_name='application_route_table')
    op.drop_table('application_route_table')
    op.drop_index(op.f('ix_application_route_response_format'), table_name='application_route_response')
    op.drop_index(op.f('ix_application_route_response_application_route_id'), table_name='application_route_response')
    op.drop_index(op.f('ix_application_route_response_application_id'), table_name='application_route_response')
    op.drop_index(op.f('ix_application_route_response_account_id'), table_name='application_route_response')
    op.drop_table('application_route_response')
    op.drop_index(op.f('ix_application_route_status'), table_name='application_route')
    op.drop_index(op.f('ix_application_route_start_application_version_id'), table_name='application_route')
    op.drop_index(op.f('ix_application_route_path'), table_name='application_route')
    op.drop_index(op.f('ix_application_route_owner_id'), table_name='application_route')
    op.drop_index(op.f('ix_application_route_method'), table_name='application_route')
    op.drop_index(op.f('ix_application_route_end_application_version_id'), table_name='application_route')
    op.drop_index(op.f('ix_application_route_application_id'), table_name='application_route')
    op.drop_index(op.f('ix_application_route_account_id'), table_name='application_route')
    op.drop_table('application_route')
    op.drop_index(op.f('ix_application_role_status'), table_name='application_role')
    op.drop_index(op.f('ix_application_role_owner_id'), table_name='application_role')
    op.drop_index(op.f('ix_application_role_application_id'), table_name='application_role')
    op.drop_index(op.f('ix_application_role_account_id'), table_name='application_role')
    op.drop_table('application_role')
    op.drop_index(op.f('ix_application_guard_type'), table_name='application_guard')
    op.drop_index(op.f('ix_application_guard_status'), table_name='application_guard')
    op.drop_index(op.f('ix_application_guard_owner_id'), table_name='application_guard')
    op.drop_index(op.f('ix_application_guard_field_type'), table_name='application_guard')
    op.drop_index(op.f('ix_application_guard_application_id'), table_name='application_guard')
    op.drop_index(op.f('ix_application_guard_account_id'), table_name='application_guard')
    op.drop_table('application_guard')
    # Drop the native Postgres enum types (autogenerate omits them).
    for enum_name in (
        'application_route_table_action',
        'application_route_table_type',
        'application_route_response_format',
        'application_route_method',
        'application_route_status',
        'application_role_status',
        'application_guard_field_format',
        'application_guard_field_type',
        'application_guard_status',
        'application_guard_type',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
