"""create application and feature tables

Revision ID: 20260708214536
Revises: 20260708190704
Create Date: 2026-07-08 23:45:36.123468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


revision: str = '20260708214536'
down_revision: Union[str, None] = '20260708190704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sa.Enum('backoffice', 'customer', 'public', 'mixed', 'other', name='application_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='application_status'), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_account_id'), 'application', ['account_id'], unique=False)
    op.create_index(op.f('ix_application_owner_id'), 'application', ['owner_id'], unique=False)
    op.create_index(op.f('ix_application_status'), 'application', ['status'], unique=False)
    op.create_index(op.f('ix_application_type'), 'application', ['type'], unique=False)
    op.create_table('feature',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('type', sa.Enum('technical', 'product', 'qa', 'data', 'ops', 'it', 'other', name='feature_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='feature_status'), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_account_id'), 'feature', ['account_id'], unique=False)
    op.create_index(op.f('ix_feature_owner_id'), 'feature', ['owner_id'], unique=False)
    op.create_index(op.f('ix_feature_status'), 'feature', ['status'], unique=False)
    op.create_index(op.f('ix_feature_type'), 'feature', ['type'], unique=False)
    op.create_table('application_environment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('production', 'pre-production', 'test', 'features', 'hotfix', 'other', name='application_environment_type'), nullable=False),
    # `application_status` is created by the `application` table above; reference
    # it here without re-creating the type.
    sa.Column('status', postgresql.ENUM('draft', 'active', 'archived', name='application_status', create_type=False), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_environment_account_id'), 'application_environment', ['account_id'], unique=False)
    op.create_index(op.f('ix_application_environment_application_id'), 'application_environment', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_environment_owner_id'), 'application_environment', ['owner_id'], unique=False)
    op.create_index(op.f('ix_application_environment_status'), 'application_environment', ['status'], unique=False)
    op.create_index(op.f('ix_application_environment_type'), 'application_environment', ['type'], unique=False)
    op.create_table('application_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('alpha', 'beta', 'stable', 'dev', name='application_version_type'), nullable=False),
    # Reuse the shared `application_status` type (created by `application`).
    sa.Column('status', postgresql.ENUM('draft', 'active', 'archived', name='application_status', create_type=False), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_version_account_id'), 'application_version', ['account_id'], unique=False)
    op.create_index(op.f('ix_application_version_application_id'), 'application_version', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_version_owner_id'), 'application_version', ['owner_id'], unique=False)
    op.create_index(op.f('ix_application_version_status'), 'application_version', ['status'], unique=False)
    op.create_index(op.f('ix_application_version_type'), 'application_version', ['type'], unique=False)
    op.create_table('feature_file',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('feature_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('screenshot', 'video', 'document', 'other', name='feature_file_type'), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'archived', name='feature_file_status'), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_extension', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_file_account_id'), 'feature_file', ['account_id'], unique=False)
    op.create_index(op.f('ix_feature_file_application_id'), 'feature_file', ['application_id'], unique=False)
    op.create_index(op.f('ix_feature_file_feature_id'), 'feature_file', ['feature_id'], unique=False)
    op.create_index(op.f('ix_feature_file_owner_id'), 'feature_file', ['owner_id'], unique=False)
    op.create_index(op.f('ix_feature_file_status'), 'feature_file', ['status'], unique=False)
    op.create_index(op.f('ix_feature_file_type'), 'feature_file', ['type'], unique=False)
    op.create_table('application_environment_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('application_environment_id', sa.Uuid(), nullable=False),
    sa.Column('application_version_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('standby', 'finished', 'error', 'cancelled', name='application_environment_version_status'), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=False),
    sa.Column('status_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['application_environment_id'], ['application_environment.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['application_version_id'], ['application_version.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_environment_version_account_id'), 'application_environment_version', ['account_id'], unique=False)
    op.create_index(op.f('ix_application_environment_version_application_environment_id'), 'application_environment_version', ['application_environment_id'], unique=False)
    op.create_index(op.f('ix_application_environment_version_application_id'), 'application_environment_version', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_environment_version_application_version_id'), 'application_environment_version', ['application_version_id'], unique=False)
    op.create_index(op.f('ix_application_environment_version_owner_id'), 'application_environment_version', ['owner_id'], unique=False)
    op.create_index(op.f('ix_application_environment_version_status'), 'application_environment_version', ['status'], unique=False)
    op.create_table('application_feature',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('feature_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('start_application_version_id', sa.Uuid(), nullable=True),
    sa.Column('end_application_version_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['end_application_version_id'], ['application_version.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['start_application_version_id'], ['application_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_feature_account_id'), 'application_feature', ['account_id'], unique=False)
    op.create_index(op.f('ix_application_feature_application_id'), 'application_feature', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_feature_end_application_version_id'), 'application_feature', ['end_application_version_id'], unique=False)
    op.create_index(op.f('ix_application_feature_feature_id'), 'application_feature', ['feature_id'], unique=False)
    op.create_index(op.f('ix_application_feature_owner_id'), 'application_feature', ['owner_id'], unique=False)
    op.create_index(op.f('ix_application_feature_start_application_version_id'), 'application_feature', ['start_application_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_feature_start_application_version_id'), table_name='application_feature')
    op.drop_index(op.f('ix_application_feature_owner_id'), table_name='application_feature')
    op.drop_index(op.f('ix_application_feature_feature_id'), table_name='application_feature')
    op.drop_index(op.f('ix_application_feature_end_application_version_id'), table_name='application_feature')
    op.drop_index(op.f('ix_application_feature_application_id'), table_name='application_feature')
    op.drop_index(op.f('ix_application_feature_account_id'), table_name='application_feature')
    op.drop_table('application_feature')
    op.drop_index(op.f('ix_application_environment_version_status'), table_name='application_environment_version')
    op.drop_index(op.f('ix_application_environment_version_owner_id'), table_name='application_environment_version')
    op.drop_index(op.f('ix_application_environment_version_application_version_id'), table_name='application_environment_version')
    op.drop_index(op.f('ix_application_environment_version_application_id'), table_name='application_environment_version')
    op.drop_index(op.f('ix_application_environment_version_application_environment_id'), table_name='application_environment_version')
    op.drop_index(op.f('ix_application_environment_version_account_id'), table_name='application_environment_version')
    op.drop_table('application_environment_version')
    op.drop_index(op.f('ix_feature_file_type'), table_name='feature_file')
    op.drop_index(op.f('ix_feature_file_status'), table_name='feature_file')
    op.drop_index(op.f('ix_feature_file_owner_id'), table_name='feature_file')
    op.drop_index(op.f('ix_feature_file_feature_id'), table_name='feature_file')
    op.drop_index(op.f('ix_feature_file_application_id'), table_name='feature_file')
    op.drop_index(op.f('ix_feature_file_account_id'), table_name='feature_file')
    op.drop_table('feature_file')
    op.drop_index(op.f('ix_application_version_type'), table_name='application_version')
    op.drop_index(op.f('ix_application_version_status'), table_name='application_version')
    op.drop_index(op.f('ix_application_version_owner_id'), table_name='application_version')
    op.drop_index(op.f('ix_application_version_application_id'), table_name='application_version')
    op.drop_index(op.f('ix_application_version_account_id'), table_name='application_version')
    op.drop_table('application_version')
    op.drop_index(op.f('ix_application_environment_type'), table_name='application_environment')
    op.drop_index(op.f('ix_application_environment_status'), table_name='application_environment')
    op.drop_index(op.f('ix_application_environment_owner_id'), table_name='application_environment')
    op.drop_index(op.f('ix_application_environment_application_id'), table_name='application_environment')
    op.drop_index(op.f('ix_application_environment_account_id'), table_name='application_environment')
    op.drop_table('application_environment')
    op.drop_index(op.f('ix_feature_type'), table_name='feature')
    op.drop_index(op.f('ix_feature_status'), table_name='feature')
    op.drop_index(op.f('ix_feature_owner_id'), table_name='feature')
    op.drop_index(op.f('ix_feature_account_id'), table_name='feature')
    op.drop_table('feature')
    op.drop_index(op.f('ix_application_type'), table_name='application')
    op.drop_index(op.f('ix_application_status'), table_name='application')
    op.drop_index(op.f('ix_application_owner_id'), table_name='application')
    op.drop_index(op.f('ix_application_account_id'), table_name='application')
    op.drop_table('application')
    # Drop the native Postgres enum types (autogenerate omits them).
    for enum_name in (
        'application_environment_version_status',
        'feature_file_status',
        'feature_file_type',
        'feature_status',
        'feature_type',
        'application_version_type',
        'application_environment_type',
        'application_status',
        'application_type',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
