# SPDX-FileCopyrightText: 2026 ChallengeMyProject
#
# SPDX-License-Identifier: AGPL-3.0-only

"""migration column subfield mapping

Revision ID: 20260719201905
Revises: 20260719201225
Create Date: 2026-07-19 22:19:05.275391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '20260719201905'
down_revision: Union[str, None] = '20260719201225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('database_migration_column', sa.Column('source_database_table_column_subfield_id', sa.Uuid(), nullable=True))
    op.add_column('database_migration_column', sa.Column('destination_database_table_column_subfield_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_database_migration_column_destination_database_table_column_subfield_id'), 'database_migration_column', ['destination_database_table_column_subfield_id'], unique=False)
    op.create_index(op.f('ix_database_migration_column_source_database_table_column_subfield_id'), 'database_migration_column', ['source_database_table_column_subfield_id'], unique=False)
    op.create_foreign_key(None, 'database_migration_column', 'database_table_column_subfield', ['source_database_table_column_subfield_id'], ['id'])
    op.create_foreign_key(None, 'database_migration_column', 'database_table_column_subfield', ['destination_database_table_column_subfield_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'database_migration_column', type_='foreignkey')
    op.drop_constraint(None, 'database_migration_column', type_='foreignkey')
    op.drop_index(op.f('ix_database_migration_column_source_database_table_column_subfield_id'), table_name='database_migration_column')
    op.drop_index(op.f('ix_database_migration_column_destination_database_table_column_subfield_id'), table_name='database_migration_column')
    op.drop_column('database_migration_column', 'destination_database_table_column_subfield_id')
    op.drop_column('database_migration_column', 'source_database_table_column_subfield_id')
    # ### end Alembic commands ###
