"""create comment table

Revision ID: 20260709040000
Revises: 20260709030000
Create Date: 2026-07-09 02:16:33.143703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '20260709040000'
down_revision: Union[str, None] = '20260709030000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('parent_comment_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('published', 'removed', name='comment_status'), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=False),
    sa.Column('entity_type', sa.Enum('feature', 'application', 'journey', 'persona', 'database', 'database_table', 'database_table_column', name='comment_entity_type'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_account_id'), 'comment', ['account_id'], unique=False)
    op.create_index(op.f('ix_comment_entity_id'), 'comment', ['entity_id'], unique=False)
    op.create_index(op.f('ix_comment_entity_type'), 'comment', ['entity_type'], unique=False)
    op.create_index(op.f('ix_comment_owner_id'), 'comment', ['owner_id'], unique=False)
    op.create_index(op.f('ix_comment_parent_comment_id'), 'comment', ['parent_comment_id'], unique=False)
    op.create_index(op.f('ix_comment_status'), 'comment', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_status'), table_name='comment')
    op.drop_index(op.f('ix_comment_parent_comment_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_owner_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_entity_type'), table_name='comment')
    op.drop_index(op.f('ix_comment_entity_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_account_id'), table_name='comment')
    op.drop_table('comment')
    op.execute('DROP TYPE IF EXISTS comment_entity_type')
    op.execute('DROP TYPE IF EXISTS comment_status')
    # ### end Alembic commands ###
