"""create database tables

Revision ID: 20260709010000
Revises: 20260709004223
Create Date: 2026-07-09 01:03:58.774282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


revision: str = '20260709010000'
down_revision: Union[str, None] = '20260709004223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_column_type',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('database_type', sa.Enum('mysql', 'postgresql', name='database_type'), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_column_type_database_type'), 'database_column_type', ['database_type'], unique=False)
    op.create_index(op.f('ix_database_column_type_slug'), 'database_column_type', ['slug'], unique=True)
    op.create_table('database',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    # `database_type` is created by the `database_column_type` table above;
    # reference it here without re-creating the type.
    sa.Column('type', postgresql.ENUM('mysql', 'postgresql', name='database_type', create_type=False), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='database_status'), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_account_id'), 'database', ['account_id'], unique=False)
    op.create_index(op.f('ix_database_owner_id'), 'database', ['owner_id'], unique=False)
    op.create_index(op.f('ix_database_status'), 'database', ['status'], unique=False)
    op.create_index(op.f('ix_database_type'), 'database', ['type'], unique=False)
    op.create_table('database_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('database_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='database_version_status'), nullable=False),
    sa.Column('version', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['database_id'], ['database.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_version_account_id'), 'database_version', ['account_id'], unique=False)
    op.create_index(op.f('ix_database_version_database_id'), 'database_version', ['database_id'], unique=False)
    op.create_index(op.f('ix_database_version_status'), 'database_version', ['status'], unique=False)
    op.create_table('database_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('database_id', sa.Uuid(), nullable=False),
    sa.Column('database_version_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('physical', 'logical', name='database_table_type'), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='database_table_status'), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=False),
    sa.Column('schema', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['database_id'], ['database.id'], ),
    sa.ForeignKeyConstraint(['database_version_id'], ['database_version.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_table_account_id'), 'database_table', ['account_id'], unique=False)
    op.create_index(op.f('ix_database_table_database_id'), 'database_table', ['database_id'], unique=False)
    op.create_index(op.f('ix_database_table_database_version_id'), 'database_table', ['database_version_id'], unique=False)
    op.create_index(op.f('ix_database_table_name'), 'database_table', ['name'], unique=False)
    op.create_index(op.f('ix_database_table_owner_id'), 'database_table', ['owner_id'], unique=False)
    op.create_index(op.f('ix_database_table_status'), 'database_table', ['status'], unique=False)
    op.create_index(op.f('ix_database_table_type'), 'database_table', ['type'], unique=False)
    op.create_table('database_table_column',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('database_table_id', sa.Uuid(), nullable=False),
    sa.Column('database_column_type_id', sa.Uuid(), nullable=False),
    sa.Column('foreign_key_database_table_id', sa.Uuid(), nullable=True),
    sa.Column('foreign_key_database_table_column_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('nullable', sa.Boolean(), nullable=False),
    sa.Column('unique', sa.Boolean(), nullable=False),
    sa.Column('default_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['database_column_type_id'], ['database_column_type.id'], ),
    sa.ForeignKeyConstraint(['database_table_id'], ['database_table.id'], ),
    sa.ForeignKeyConstraint(['foreign_key_database_table_column_id'], ['database_table_column.id'], ),
    sa.ForeignKeyConstraint(['foreign_key_database_table_id'], ['database_table.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_table_column_account_id'), 'database_table_column', ['account_id'], unique=False)
    op.create_index(op.f('ix_database_table_column_database_column_type_id'), 'database_table_column', ['database_column_type_id'], unique=False)
    op.create_index(op.f('ix_database_table_column_database_table_id'), 'database_table_column', ['database_table_id'], unique=False)
    op.create_index(op.f('ix_database_table_column_foreign_key_database_table_column_id'), 'database_table_column', ['foreign_key_database_table_column_id'], unique=False)
    op.create_index(op.f('ix_database_table_column_foreign_key_database_table_id'), 'database_table_column', ['foreign_key_database_table_id'], unique=False)
    op.create_index(op.f('ix_database_table_column_name'), 'database_table_column', ['name'], unique=False)
    op.create_index(op.f('ix_database_table_column_owner_id'), 'database_table_column', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_database_table_column_owner_id'), table_name='database_table_column')
    op.drop_index(op.f('ix_database_table_column_name'), table_name='database_table_column')
    op.drop_index(op.f('ix_database_table_column_foreign_key_database_table_id'), table_name='database_table_column')
    op.drop_index(op.f('ix_database_table_column_foreign_key_database_table_column_id'), table_name='database_table_column')
    op.drop_index(op.f('ix_database_table_column_database_table_id'), table_name='database_table_column')
    op.drop_index(op.f('ix_database_table_column_database_column_type_id'), table_name='database_table_column')
    op.drop_index(op.f('ix_database_table_column_account_id'), table_name='database_table_column')
    op.drop_table('database_table_column')
    op.drop_index(op.f('ix_database_table_type'), table_name='database_table')
    op.drop_index(op.f('ix_database_table_status'), table_name='database_table')
    op.drop_index(op.f('ix_database_table_owner_id'), table_name='database_table')
    op.drop_index(op.f('ix_database_table_name'), table_name='database_table')
    op.drop_index(op.f('ix_database_table_database_version_id'), table_name='database_table')
    op.drop_index(op.f('ix_database_table_database_id'), table_name='database_table')
    op.drop_index(op.f('ix_database_table_account_id'), table_name='database_table')
    op.drop_table('database_table')
    op.drop_index(op.f('ix_database_version_status'), table_name='database_version')
    op.drop_index(op.f('ix_database_version_database_id'), table_name='database_version')
    op.drop_index(op.f('ix_database_version_account_id'), table_name='database_version')
    op.drop_table('database_version')
    op.drop_index(op.f('ix_database_type'), table_name='database')
    op.drop_index(op.f('ix_database_status'), table_name='database')
    op.drop_index(op.f('ix_database_owner_id'), table_name='database')
    op.drop_index(op.f('ix_database_account_id'), table_name='database')
    op.drop_table('database')
    op.drop_index(op.f('ix_database_column_type_slug'), table_name='database_column_type')
    op.drop_index(op.f('ix_database_column_type_database_type'), table_name='database_column_type')
    op.drop_table('database_column_type')
    # Drop the native Postgres enum types (autogenerate omits them).
    for enum_name in (
        'database_table_status',
        'database_table_type',
        'database_version_status',
        'database_status',
        'database_type',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
