"""create tag table and add tag_ids

Revision ID: 20260709030000
Revises: 20260709020000
Create Date: 2026-07-09 02:07:37.287724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '20260709030000'
down_revision: Union[str, None] = '20260709020000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('application', 'application_route', 'application_guard', 'feature', 'journey', 'journey_scenario', 'journey_scenario_step', 'persona', 'database', 'database_table', name='tag_entity_type'), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('background_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_account_id'), 'tag', ['account_id'], unique=False)
    op.create_index(op.f('ix_tag_entity_type'), 'tag', ['entity_type'], unique=False)
    op.add_column('application', sa.Column('tag_ids', sa.ARRAY(sa.Uuid()), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('application_guard', sa.Column('tag_ids', sa.ARRAY(sa.Uuid()), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('application_route', sa.Column('tag_ids', sa.ARRAY(sa.Uuid()), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('database', sa.Column('tag_ids', sa.ARRAY(sa.Uuid()), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('database_table', sa.Column('tag_ids', sa.ARRAY(sa.Uuid()), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('feature', sa.Column('tag_ids', sa.ARRAY(sa.Uuid()), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('journey', sa.Column('tag_ids', sa.ARRAY(sa.Uuid()), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('journey_scenario', sa.Column('tag_ids', sa.ARRAY(sa.Uuid()), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('journey_scenario_step', sa.Column('tag_ids', sa.ARRAY(sa.Uuid()), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('persona', sa.Column('tag_ids', sa.ARRAY(sa.Uuid()), nullable=False, server_default=sa.text("'{}'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persona', 'tag_ids')
    op.drop_column('journey_scenario_step', 'tag_ids')
    op.drop_column('journey_scenario', 'tag_ids')
    op.drop_column('journey', 'tag_ids')
    op.drop_column('feature', 'tag_ids')
    op.drop_column('database_table', 'tag_ids')
    op.drop_column('database', 'tag_ids')
    op.drop_column('application_route', 'tag_ids')
    op.drop_column('application_guard', 'tag_ids')
    op.drop_column('application', 'tag_ids')
    op.drop_index(op.f('ix_tag_entity_type'), table_name='tag')
    op.drop_index(op.f('ix_tag_account_id'), table_name='tag')
    op.drop_table('tag')
    op.execute('DROP TYPE IF EXISTS tag_entity_type')
    # ### end Alembic commands ###
