"""create database migration tables

Migrations can be commented, so `comment_entity_type` gains the two new members.

Revision ID: 20260709141334
Revises: 20260709140000
Create Date: 2026-07-09 16:13:34.519858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '20260709141334'
down_revision: Union[str, None] = '20260709140000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# `comment_entity_type` members, in order, before the migration ones are appended.
_COMMENT_ENTITY_TYPE_WITHOUT_MIGRATIONS = (
    'feature',
    'application',
    'application_route',
    'journey',
    'persona',
    'database',
    'database_table',
    'database_table_column',
    'service',
    'service_action',
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_migration',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('source_database_id', sa.Uuid(), nullable=False),
    sa.Column('source_database_version_id', sa.Uuid(), nullable=False),
    sa.Column('destination_database_id', sa.Uuid(), nullable=False),
    sa.Column('destination_database_version_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('minor', 'major', name='database_migration_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'validated', 'completed', 'cancelled', name='database_migration_status'), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['destination_database_id'], ['database.id'], ),
    sa.ForeignKeyConstraint(['destination_database_version_id'], ['database_version.id'], ),
    sa.ForeignKeyConstraint(['source_database_id'], ['database.id'], ),
    sa.ForeignKeyConstraint(['source_database_version_id'], ['database_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_migration_account_id'), 'database_migration', ['account_id'], unique=False)
    op.create_index(op.f('ix_database_migration_destination_database_id'), 'database_migration', ['destination_database_id'], unique=False)
    op.create_index(op.f('ix_database_migration_destination_database_version_id'), 'database_migration', ['destination_database_version_id'], unique=False)
    op.create_index(op.f('ix_database_migration_source_database_id'), 'database_migration', ['source_database_id'], unique=False)
    op.create_index(op.f('ix_database_migration_source_database_version_id'), 'database_migration', ['source_database_version_id'], unique=False)
    op.create_index(op.f('ix_database_migration_status'), 'database_migration', ['status'], unique=False)
    op.create_index(op.f('ix_database_migration_title'), 'database_migration', ['title'], unique=False)
    op.create_table('database_migration_column',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('database_migration_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('source_database_table_id', sa.Uuid(), nullable=True),
    sa.Column('source_database_table_column_id', sa.Uuid(), nullable=True),
    sa.Column('destination_database_table_id', sa.Uuid(), nullable=True),
    sa.Column('destination_database_table_column_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('migration', 'deletion', 'creation', name='database_migration_column_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'to_be_confirmed', 'confirmed', name='database_migration_column_status'), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=False),
    sa.Column('transformation_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['database_migration_id'], ['database_migration.id'], ),
    sa.ForeignKeyConstraint(['destination_database_table_column_id'], ['database_table_column.id'], ),
    sa.ForeignKeyConstraint(['destination_database_table_id'], ['database_table.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['source_database_table_column_id'], ['database_table_column.id'], ),
    sa.ForeignKeyConstraint(['source_database_table_id'], ['database_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_migration_column_account_id'), 'database_migration_column', ['account_id'], unique=False)
    op.create_index(op.f('ix_database_migration_column_database_migration_id'), 'database_migration_column', ['database_migration_id'], unique=False)
    op.create_index(op.f('ix_database_migration_column_destination_database_table_column_id'), 'database_migration_column', ['destination_database_table_column_id'], unique=False)
    op.create_index(op.f('ix_database_migration_column_destination_database_table_id'), 'database_migration_column', ['destination_database_table_id'], unique=False)
    op.create_index(op.f('ix_database_migration_column_owner_id'), 'database_migration_column', ['owner_id'], unique=False)
    op.create_index(op.f('ix_database_migration_column_source_database_table_column_id'), 'database_migration_column', ['source_database_table_column_id'], unique=False)
    op.create_index(op.f('ix_database_migration_column_source_database_table_id'), 'database_migration_column', ['source_database_table_id'], unique=False)
    op.create_index(op.f('ix_database_migration_column_status'), 'database_migration_column', ['status'], unique=False)
    # ### end Alembic commands ###
    # `comment_entity_type` already exists: append the two new members. No
    # `AFTER <value>` clause — referencing a value added in the same transaction
    # is rejected by Postgres, and appending matches the Python enum order.
    op.execute("ALTER TYPE comment_entity_type ADD VALUE IF NOT EXISTS 'database_migration'")
    op.execute("ALTER TYPE comment_entity_type ADD VALUE IF NOT EXISTS 'database_migration_column'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_database_migration_column_status'), table_name='database_migration_column')
    op.drop_index(op.f('ix_database_migration_column_source_database_table_id'), table_name='database_migration_column')
    op.drop_index(op.f('ix_database_migration_column_source_database_table_column_id'), table_name='database_migration_column')
    op.drop_index(op.f('ix_database_migration_column_owner_id'), table_name='database_migration_column')
    op.drop_index(op.f('ix_database_migration_column_destination_database_table_id'), table_name='database_migration_column')
    op.drop_index(op.f('ix_database_migration_column_destination_database_table_column_id'), table_name='database_migration_column')
    op.drop_index(op.f('ix_database_migration_column_database_migration_id'), table_name='database_migration_column')
    op.drop_index(op.f('ix_database_migration_column_account_id'), table_name='database_migration_column')
    op.drop_table('database_migration_column')
    op.drop_index(op.f('ix_database_migration_title'), table_name='database_migration')
    op.drop_index(op.f('ix_database_migration_status'), table_name='database_migration')
    op.drop_index(op.f('ix_database_migration_source_database_version_id'), table_name='database_migration')
    op.drop_index(op.f('ix_database_migration_source_database_id'), table_name='database_migration')
    op.drop_index(op.f('ix_database_migration_destination_database_version_id'), table_name='database_migration')
    op.drop_index(op.f('ix_database_migration_destination_database_id'), table_name='database_migration')
    op.drop_index(op.f('ix_database_migration_account_id'), table_name='database_migration')
    op.drop_table('database_migration')
    # ### end Alembic commands ###
    # Drop the native Postgres enum types (autogenerate omits them).
    for enum_name in (
        'database_migration_column_status',
        'database_migration_column_type',
        'database_migration_status',
        'database_migration_type',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # Postgres cannot drop an enum value in place: recreate `comment_entity_type`
    # without the migration members, after removing the comments that used them.
    values = ", ".join(f"'{value}'" for value in _COMMENT_ENTITY_TYPE_WITHOUT_MIGRATIONS)
    op.execute(
        "DELETE FROM comment WHERE entity_type IN "
        "('database_migration', 'database_migration_column')"
    )
    op.execute('ALTER TYPE comment_entity_type RENAME TO comment_entity_type_old')
    op.execute(f'CREATE TYPE comment_entity_type AS ENUM ({values})')
    op.execute(
        'ALTER TABLE comment ALTER COLUMN entity_type TYPE comment_entity_type '
        'USING entity_type::text::comment_entity_type'
    )
    op.execute('DROP TYPE comment_entity_type_old')
