# SPDX-FileCopyrightText: 2026 ChallengeMyProject
#
# SPDX-License-Identifier: AGPL-3.0-only

"""database table column subfield

Revision ID: 20260719201225
Revises: 20260719195322
Create Date: 2026-07-19 22:12:25.159425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '20260719201225'
down_revision: Union[str, None] = '20260719195322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_table_column_subfield',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('database_table_column_id', sa.Uuid(), nullable=False),
    sa.Column('parent_subfield_id', sa.Uuid(), nullable=True),
    sa.Column('database_column_type_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nullable', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['database_column_type_id'], ['database_column_type.id'], ),
    sa.ForeignKeyConstraint(['database_table_column_id'], ['database_table_column.id'], ),
    sa.ForeignKeyConstraint(['parent_subfield_id'], ['database_table_column_subfield.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_table_column_subfield_account_id'), 'database_table_column_subfield', ['account_id'], unique=False)
    op.create_index(op.f('ix_database_table_column_subfield_database_column_type_id'), 'database_table_column_subfield', ['database_column_type_id'], unique=False)
    op.create_index(op.f('ix_database_table_column_subfield_database_table_column_id'), 'database_table_column_subfield', ['database_table_column_id'], unique=False)
    op.create_index(op.f('ix_database_table_column_subfield_name'), 'database_table_column_subfield', ['name'], unique=False)
    op.create_index(op.f('ix_database_table_column_subfield_parent_subfield_id'), 'database_table_column_subfield', ['parent_subfield_id'], unique=False)
    op.create_index(op.f('ix_database_table_column_subfield_rank'), 'database_table_column_subfield', ['rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_database_table_column_subfield_rank'), table_name='database_table_column_subfield')
    op.drop_index(op.f('ix_database_table_column_subfield_parent_subfield_id'), table_name='database_table_column_subfield')
    op.drop_index(op.f('ix_database_table_column_subfield_name'), table_name='database_table_column_subfield')
    op.drop_index(op.f('ix_database_table_column_subfield_database_table_column_id'), table_name='database_table_column_subfield')
    op.drop_index(op.f('ix_database_table_column_subfield_database_column_type_id'), table_name='database_table_column_subfield')
    op.drop_index(op.f('ix_database_table_column_subfield_account_id'), table_name='database_table_column_subfield')
    op.drop_table('database_table_column_subfield')
    # ### end Alembic commands ###
