# SPDX-FileCopyrightText: 2026 ChallengeMyProject
#
# SPDX-License-Identifier: AGPL-3.0-only

"""create service tables

Revision ID: 20260709124552
Revises: 20260709050000
Create Date: 2026-07-09 14:45:52.337791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '20260709124552'
down_revision: Union[str, None] = '20260709050000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# `comment_entity_type` members, in order, before the service ones are appended.
_COMMENT_ENTITY_TYPE_WITHOUT_SERVICES = (
    'feature',
    'application',
    'application_route',
    'journey',
    'persona',
    'database',
    'database_table',
    'database_table_column',
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('internal', 'external', 'third_party', 'other', name='service_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='service_status'), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('picture_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('openapi_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_account_id'), 'service', ['account_id'], unique=False)
    op.create_index(op.f('ix_service_owner_id'), 'service', ['owner_id'], unique=False)
    op.create_index(op.f('ix_service_status'), 'service', ['status'], unique=False)
    op.create_index(op.f('ix_service_type'), 'service', ['type'], unique=False)
    op.create_table('service_action',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('endpoint', 'webhook', 'event', 'job', 'other', name='service_action_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='service_action_status'), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('method', sa.Enum('POST', 'GET', 'PATCH', 'PUT', 'DELETE', 'QUERY', name='service_action_method'), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_action_account_id'), 'service_action', ['account_id'], unique=False)
    op.create_index(op.f('ix_service_action_method'), 'service_action', ['method'], unique=False)
    op.create_index(op.f('ix_service_action_owner_id'), 'service_action', ['owner_id'], unique=False)
    op.create_index(op.f('ix_service_action_path'), 'service_action', ['path'], unique=False)
    op.create_index(op.f('ix_service_action_service_id'), 'service_action', ['service_id'], unique=False)
    op.create_index(op.f('ix_service_action_status'), 'service_action', ['status'], unique=False)
    op.create_index(op.f('ix_service_action_type'), 'service_action', ['type'], unique=False)
    # ### end Alembic commands ###
    # `comment_entity_type` already exists: append the two new members. No
    # `AFTER <value>` clause — referencing a value added in the same transaction
    # is rejected by Postgres, and appending matches the Python enum order.
    op.execute("ALTER TYPE comment_entity_type ADD VALUE IF NOT EXISTS 'service'")
    op.execute("ALTER TYPE comment_entity_type ADD VALUE IF NOT EXISTS 'service_action'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_action_type'), table_name='service_action')
    op.drop_index(op.f('ix_service_action_status'), table_name='service_action')
    op.drop_index(op.f('ix_service_action_service_id'), table_name='service_action')
    op.drop_index(op.f('ix_service_action_path'), table_name='service_action')
    op.drop_index(op.f('ix_service_action_owner_id'), table_name='service_action')
    op.drop_index(op.f('ix_service_action_method'), table_name='service_action')
    op.drop_index(op.f('ix_service_action_account_id'), table_name='service_action')
    op.drop_table('service_action')
    op.drop_index(op.f('ix_service_type'), table_name='service')
    op.drop_index(op.f('ix_service_status'), table_name='service')
    op.drop_index(op.f('ix_service_owner_id'), table_name='service')
    op.drop_index(op.f('ix_service_account_id'), table_name='service')
    op.drop_table('service')
    # ### end Alembic commands ###
    # Drop the native Postgres enum types (autogenerate omits them).
    for enum_name in (
        'service_action_method',
        'service_action_status',
        'service_action_type',
        'service_status',
        'service_type',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # Postgres cannot drop an enum value in place: recreate `comment_entity_type`
    # without the service members, after removing the comments that used them.
    values = ", ".join(f"'{value}'" for value in _COMMENT_ENTITY_TYPE_WITHOUT_SERVICES)
    op.execute("DELETE FROM comment WHERE entity_type IN ('service', 'service_action')")
    op.execute('ALTER TYPE comment_entity_type RENAME TO comment_entity_type_old')
    op.execute(f'CREATE TYPE comment_entity_type AS ENUM ({values})')
    op.execute(
        'ALTER TABLE comment ALTER COLUMN entity_type TYPE comment_entity_type '
        'USING entity_type::text::comment_entity_type'
    )
    op.execute('DROP TYPE comment_entity_type_old')
