"""create persona journey and core tables

Revision ID: 20260708224056
Revises: 20260708214536
Create Date: 2026-07-09 00:40:56.988918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '20260708224056'
down_revision: Union[str, None] = '20260708214536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_type',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.Enum('navigate', 'form', 'assert', name='action_type_category'), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parameter_schema', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_type_slug'), 'action_type', ['slug'], unique=True)
    op.create_index(op.f('ix_action_type_type'), 'action_type', ['type'], unique=False)
    op.create_table('assertion_type',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.Enum('browser', 'database', name='assertion_type_category'), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parameter_schema', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assertion_type_slug'), 'assertion_type', ['slug'], unique=True)
    op.create_index(op.f('ix_assertion_type_type'), 'assertion_type', ['type'], unique=False)
    op.create_table('journey',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('business', 'customer', 'internal', 'other', name='journey_type'), nullable=False),
    sa.Column('personas_ids', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='journey_status'), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_account_id'), 'journey', ['account_id'], unique=False)
    op.create_index(op.f('ix_journey_owner_id'), 'journey', ['owner_id'], unique=False)
    op.create_index(op.f('ix_journey_status'), 'journey', ['status'], unique=False)
    op.create_index(op.f('ix_journey_type'), 'journey', ['type'], unique=False)
    op.create_table('persona',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('customer', 'business', 'internal', 'other', name='persona_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='persona_status'), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_account_id'), 'persona', ['account_id'], unique=False)
    op.create_index(op.f('ix_persona_status'), 'persona', ['status'], unique=False)
    op.create_index(op.f('ix_persona_type'), 'persona', ['type'], unique=False)
    op.create_table('feature_journey',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('feature_id', sa.Uuid(), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ),
    sa.ForeignKeyConstraint(['journey_id'], ['journey.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_journey_account_id'), 'feature_journey', ['account_id'], unique=False)
    op.create_index(op.f('ix_feature_journey_feature_id'), 'feature_journey', ['feature_id'], unique=False)
    op.create_index(op.f('ix_feature_journey_journey_id'), 'feature_journey', ['journey_id'], unique=False)
    op.create_index(op.f('ix_feature_journey_owner_id'), 'feature_journey', ['owner_id'], unique=False)
    op.create_table('journey_scenario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('nominal', 'alternative', 'error', 'edge_case', name='journey_scenario_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='journey_scenario_status'), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=False),
    sa.Column('personas_ids', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('criticity', sa.Enum('low', 'medium', 'high', 'critical', name='journey_scenario_criticity'), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['journey_id'], ['journey.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_scenario_account_id'), 'journey_scenario', ['account_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_criticity'), 'journey_scenario', ['criticity'], unique=False)
    op.create_index(op.f('ix_journey_scenario_journey_id'), 'journey_scenario', ['journey_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_owner_id'), 'journey_scenario', ['owner_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_status'), 'journey_scenario', ['status'], unique=False)
    op.create_index(op.f('ix_journey_scenario_type'), 'journey_scenario', ['type'], unique=False)
    op.create_table('journey_scenario_step',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('journey_scenario_id', sa.Uuid(), nullable=False),
    sa.Column('parent_journey_scenario_step_id', sa.Uuid(), nullable=True),
    sa.Column('action_type_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('optional', sa.Boolean(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['action_type_id'], ['action_type.id'], ),
    sa.ForeignKeyConstraint(['journey_id'], ['journey.id'], ),
    sa.ForeignKeyConstraint(['journey_scenario_id'], ['journey_scenario.id'], ),
    sa.ForeignKeyConstraint(['parent_journey_scenario_step_id'], ['journey_scenario_step.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_scenario_step_account_id'), 'journey_scenario_step', ['account_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_step_action_type_id'), 'journey_scenario_step', ['action_type_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_step_journey_id'), 'journey_scenario_step', ['journey_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_step_journey_scenario_id'), 'journey_scenario_step', ['journey_scenario_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_step_parent_journey_scenario_step_id'), 'journey_scenario_step', ['parent_journey_scenario_step_id'], unique=False)
    op.create_table('journey_scenario_step_assertion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('journey_scenario_id', sa.Uuid(), nullable=False),
    sa.Column('journey_scenario_step_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('assertion_type_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='journey_scenario_step_assertion_status'), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['assertion_type_id'], ['assertion_type.id'], ),
    sa.ForeignKeyConstraint(['journey_id'], ['journey.id'], ),
    sa.ForeignKeyConstraint(['journey_scenario_id'], ['journey_scenario.id'], ),
    sa.ForeignKeyConstraint(['journey_scenario_step_id'], ['journey_scenario_step.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_scenario_step_assertion_account_id'), 'journey_scenario_step_assertion', ['account_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_step_assertion_assertion_type_id'), 'journey_scenario_step_assertion', ['assertion_type_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_step_assertion_journey_id'), 'journey_scenario_step_assertion', ['journey_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_step_assertion_journey_scenario_id'), 'journey_scenario_step_assertion', ['journey_scenario_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_step_assertion_journey_scenario_step_id'), 'journey_scenario_step_assertion', ['journey_scenario_step_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_step_assertion_owner_id'), 'journey_scenario_step_assertion', ['owner_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_step_assertion_status'), 'journey_scenario_step_assertion', ['status'], unique=False)
    op.create_table('journey_scenario_step_file',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('journey_scenario_id', sa.Uuid(), nullable=False),
    sa.Column('journey_scenario_step_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('screenshot', 'video', 'document', 'input', 'other', name='journey_scenario_step_file_type'), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'archived', name='journey_scenario_step_file_status'), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_extension', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['journey_id'], ['journey.id'], ),
    sa.ForeignKeyConstraint(['journey_scenario_id'], ['journey_scenario.id'], ),
    sa.ForeignKeyConstraint(['journey_scenario_step_id'], ['journey_scenario_step.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_scenario_step_file_account_id'), 'journey_scenario_step_file', ['account_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_step_file_journey_id'), 'journey_scenario_step_file', ['journey_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_step_file_journey_scenario_id'), 'journey_scenario_step_file', ['journey_scenario_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_step_file_journey_scenario_step_id'), 'journey_scenario_step_file', ['journey_scenario_step_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_step_file_owner_id'), 'journey_scenario_step_file', ['owner_id'], unique=False)
    op.create_index(op.f('ix_journey_scenario_step_file_status'), 'journey_scenario_step_file', ['status'], unique=False)
    op.create_index(op.f('ix_journey_scenario_step_file_type'), 'journey_scenario_step_file', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journey_scenario_step_file_type'), table_name='journey_scenario_step_file')
    op.drop_index(op.f('ix_journey_scenario_step_file_status'), table_name='journey_scenario_step_file')
    op.drop_index(op.f('ix_journey_scenario_step_file_owner_id'), table_name='journey_scenario_step_file')
    op.drop_index(op.f('ix_journey_scenario_step_file_journey_scenario_step_id'), table_name='journey_scenario_step_file')
    op.drop_index(op.f('ix_journey_scenario_step_file_journey_scenario_id'), table_name='journey_scenario_step_file')
    op.drop_index(op.f('ix_journey_scenario_step_file_journey_id'), table_name='journey_scenario_step_file')
    op.drop_index(op.f('ix_journey_scenario_step_file_account_id'), table_name='journey_scenario_step_file')
    op.drop_table('journey_scenario_step_file')
    op.drop_index(op.f('ix_journey_scenario_step_assertion_status'), table_name='journey_scenario_step_assertion')
    op.drop_index(op.f('ix_journey_scenario_step_assertion_owner_id'), table_name='journey_scenario_step_assertion')
    op.drop_index(op.f('ix_journey_scenario_step_assertion_journey_scenario_step_id'), table_name='journey_scenario_step_assertion')
    op.drop_index(op.f('ix_journey_scenario_step_assertion_journey_scenario_id'), table_name='journey_scenario_step_assertion')
    op.drop_index(op.f('ix_journey_scenario_step_assertion_journey_id'), table_name='journey_scenario_step_assertion')
    op.drop_index(op.f('ix_journey_scenario_step_assertion_assertion_type_id'), table_name='journey_scenario_step_assertion')
    op.drop_index(op.f('ix_journey_scenario_step_assertion_account_id'), table_name='journey_scenario_step_assertion')
    op.drop_table('journey_scenario_step_assertion')
    op.drop_index(op.f('ix_journey_scenario_step_parent_journey_scenario_step_id'), table_name='journey_scenario_step')
    op.drop_index(op.f('ix_journey_scenario_step_journey_scenario_id'), table_name='journey_scenario_step')
    op.drop_index(op.f('ix_journey_scenario_step_journey_id'), table_name='journey_scenario_step')
    op.drop_index(op.f('ix_journey_scenario_step_action_type_id'), table_name='journey_scenario_step')
    op.drop_index(op.f('ix_journey_scenario_step_account_id'), table_name='journey_scenario_step')
    op.drop_table('journey_scenario_step')
    op.drop_index(op.f('ix_journey_scenario_type'), table_name='journey_scenario')
    op.drop_index(op.f('ix_journey_scenario_status'), table_name='journey_scenario')
    op.drop_index(op.f('ix_journey_scenario_owner_id'), table_name='journey_scenario')
    op.drop_index(op.f('ix_journey_scenario_journey_id'), table_name='journey_scenario')
    op.drop_index(op.f('ix_journey_scenario_criticity'), table_name='journey_scenario')
    op.drop_index(op.f('ix_journey_scenario_account_id'), table_name='journey_scenario')
    op.drop_table('journey_scenario')
    op.drop_index(op.f('ix_feature_journey_owner_id'), table_name='feature_journey')
    op.drop_index(op.f('ix_feature_journey_journey_id'), table_name='feature_journey')
    op.drop_index(op.f('ix_feature_journey_feature_id'), table_name='feature_journey')
    op.drop_index(op.f('ix_feature_journey_account_id'), table_name='feature_journey')
    op.drop_table('feature_journey')
    op.drop_index(op.f('ix_persona_type'), table_name='persona')
    op.drop_index(op.f('ix_persona_status'), table_name='persona')
    op.drop_index(op.f('ix_persona_account_id'), table_name='persona')
    op.drop_table('persona')
    op.drop_index(op.f('ix_journey_type'), table_name='journey')
    op.drop_index(op.f('ix_journey_status'), table_name='journey')
    op.drop_index(op.f('ix_journey_owner_id'), table_name='journey')
    op.drop_index(op.f('ix_journey_account_id'), table_name='journey')
    op.drop_table('journey')
    op.drop_index(op.f('ix_assertion_type_type'), table_name='assertion_type')
    op.drop_index(op.f('ix_assertion_type_slug'), table_name='assertion_type')
    op.drop_table('assertion_type')
    op.drop_index(op.f('ix_action_type_type'), table_name='action_type')
    op.drop_index(op.f('ix_action_type_slug'), table_name='action_type')
    op.drop_table('action_type')
    # Drop the native Postgres enum types (autogenerate omits them).
    for enum_name in (
        'journey_scenario_step_assertion_status',
        'journey_scenario_step_file_status',
        'journey_scenario_step_file_type',
        'journey_scenario_criticity',
        'journey_scenario_status',
        'journey_scenario_type',
        'journey_status',
        'journey_type',
        'assertion_type_category',
        'action_type_category',
        'persona_status',
        'persona_type',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
