"""create user and authentication tables

Revision ID: 20260708124621
Revises: 
Create Date: 2026-07-08 14:46:21.739899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '20260708124621'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activation_date', sa.DateTime(), nullable=True),
    sa.Column('activation_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activation_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activation_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_authentication_date', sa.DateTime(), nullable=True),
    sa.Column('last_authentication_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_authentication_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_authentication_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gender', sa.Enum('unknown', 'male', 'female', name='user_gender'), nullable=False),
    sa.Column('type', sa.Enum('physical', 'application', name='user_type'), nullable=False),
    sa.Column('status', sa.Enum('active', 'removed', 'blocked', name='user_status'), nullable=False),
    sa.Column('language', sa.Enum('fr-FR', 'en-GB', 'es-ES', 'de-DE', 'it-IT', name='language'), nullable=False),
    sa.Column('theme', sa.Enum('system', 'light', 'dark', name='user_theme'), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('picture_profile', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('token_control', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activation_ip'), 'user', ['activation_ip'], unique=False)
    op.create_index(op.f('ix_user_created_ip'), 'user', ['created_ip'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_gender'), 'user', ['gender'], unique=False)
    op.create_index(op.f('ix_user_language'), 'user', ['language'], unique=False)
    op.create_index(op.f('ix_user_last_authentication_ip'), 'user', ['last_authentication_ip'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=False)
    op.create_index(op.f('ix_user_status'), 'user', ['status'], unique=False)
    op.create_index(op.f('ix_user_type'), 'user', ['type'], unique=False)
    op.create_table('user_authentication',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activation_date', sa.DateTime(), nullable=True),
    sa.Column('activation_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activation_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activation_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_authentication_date', sa.DateTime(), nullable=True),
    sa.Column('last_authentication_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_authentication_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_authentication_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sa.Enum('email_password', 'google_oauth', name='user_authentication_type'), nullable=False),
    sa.Column('status', sa.Enum('not_verified', 'active', 'blocked', name='user_authentication_status'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'email', name='unique_user_authentication')
    )
    op.create_index(op.f('ix_user_authentication_activation_ip'), 'user_authentication', ['activation_ip'], unique=False)
    op.create_index(op.f('ix_user_authentication_created_ip'), 'user_authentication', ['created_ip'], unique=False)
    op.create_index(op.f('ix_user_authentication_email'), 'user_authentication', ['email'], unique=False)
    op.create_index(op.f('ix_user_authentication_last_authentication_ip'), 'user_authentication', ['last_authentication_ip'], unique=False)
    op.create_index(op.f('ix_user_authentication_status'), 'user_authentication', ['status'], unique=False)
    op.create_index(op.f('ix_user_authentication_type'), 'user_authentication', ['type'], unique=False)
    op.create_index(op.f('ix_user_authentication_user_id'), 'user_authentication', ['user_id'], unique=False)
    op.create_table('user_authentication_two_factor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('activation_date', sa.DateTime(), nullable=True),
    sa.Column('activation_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activation_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activation_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_authentication_date', sa.DateTime(), nullable=True),
    sa.Column('last_authentication_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_authentication_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_authentication_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('otp', 'recovery_code', 'u2f', name='user_authentication_two_factor_type'), nullable=False),
    sa.Column('status', sa.Enum('not_verified', 'active', 'used', 'disabled', 'blocked', name='user_authentication_two_factor_status'), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_authentication_two_factor_activation_ip'), 'user_authentication_two_factor', ['activation_ip'], unique=False)
    op.create_index(op.f('ix_user_authentication_two_factor_last_authentication_ip'), 'user_authentication_two_factor', ['last_authentication_ip'], unique=False)
    op.create_index(op.f('ix_user_authentication_two_factor_status'), 'user_authentication_two_factor', ['status'], unique=False)
    op.create_index(op.f('ix_user_authentication_two_factor_type'), 'user_authentication_two_factor', ['type'], unique=False)
    op.create_index(op.f('ix_user_authentication_two_factor_user_id'), 'user_authentication_two_factor', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_authentication_two_factor_value'), 'user_authentication_two_factor', ['value'], unique=False)
    op.create_table('user_authentication_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('user_authentication_id', sa.Uuid(), nullable=True),
    sa.Column('user_authentication_two_factor_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('authentication_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('authentication_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('authentication_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sa.Enum('register', 'activate', 'activation_link', 'email_password', 'google_oauth', 'two_factor_otp', 'two_factor_u2f', 'two_factor_recovery_code', 'refresh_token', 'forgot_password', 'reset_password', 'access', name='user_authentication_log_type'), nullable=False),
    sa.Column('status', sa.Enum('success', 'error', 'forbidden', name='user_authentication_log_status'), nullable=False),
    sa.ForeignKeyConstraint(['user_authentication_id'], ['user_authentication.id'], ),
    sa.ForeignKeyConstraint(['user_authentication_two_factor_id'], ['user_authentication_two_factor.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_authentication_log_authentication_ip'), 'user_authentication_log', ['authentication_ip'], unique=False)
    op.create_index(op.f('ix_user_authentication_log_status'), 'user_authentication_log', ['status'], unique=False)
    op.create_index(op.f('ix_user_authentication_log_type'), 'user_authentication_log', ['type'], unique=False)
    op.create_index(op.f('ix_user_authentication_log_user_authentication_id'), 'user_authentication_log', ['user_authentication_id'], unique=False)
    op.create_index(op.f('ix_user_authentication_log_user_authentication_two_factor_id'), 'user_authentication_log', ['user_authentication_two_factor_id'], unique=False)
    op.create_index(op.f('ix_user_authentication_log_user_id'), 'user_authentication_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_authentication_log_user_id'), table_name='user_authentication_log')
    op.drop_index(op.f('ix_user_authentication_log_user_authentication_two_factor_id'), table_name='user_authentication_log')
    op.drop_index(op.f('ix_user_authentication_log_user_authentication_id'), table_name='user_authentication_log')
    op.drop_index(op.f('ix_user_authentication_log_type'), table_name='user_authentication_log')
    op.drop_index(op.f('ix_user_authentication_log_status'), table_name='user_authentication_log')
    op.drop_index(op.f('ix_user_authentication_log_authentication_ip'), table_name='user_authentication_log')
    op.drop_table('user_authentication_log')
    op.drop_index(op.f('ix_user_authentication_two_factor_value'), table_name='user_authentication_two_factor')
    op.drop_index(op.f('ix_user_authentication_two_factor_user_id'), table_name='user_authentication_two_factor')
    op.drop_index(op.f('ix_user_authentication_two_factor_type'), table_name='user_authentication_two_factor')
    op.drop_index(op.f('ix_user_authentication_two_factor_status'), table_name='user_authentication_two_factor')
    op.drop_index(op.f('ix_user_authentication_two_factor_last_authentication_ip'), table_name='user_authentication_two_factor')
    op.drop_index(op.f('ix_user_authentication_two_factor_activation_ip'), table_name='user_authentication_two_factor')
    op.drop_table('user_authentication_two_factor')
    op.drop_index(op.f('ix_user_authentication_user_id'), table_name='user_authentication')
    op.drop_index(op.f('ix_user_authentication_type'), table_name='user_authentication')
    op.drop_index(op.f('ix_user_authentication_status'), table_name='user_authentication')
    op.drop_index(op.f('ix_user_authentication_last_authentication_ip'), table_name='user_authentication')
    op.drop_index(op.f('ix_user_authentication_email'), table_name='user_authentication')
    op.drop_index(op.f('ix_user_authentication_created_ip'), table_name='user_authentication')
    op.drop_index(op.f('ix_user_authentication_activation_ip'), table_name='user_authentication')
    op.drop_table('user_authentication')
    op.drop_index(op.f('ix_user_type'), table_name='user')
    op.drop_index(op.f('ix_user_status'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_last_authentication_ip'), table_name='user')
    op.drop_index(op.f('ix_user_language'), table_name='user')
    op.drop_index(op.f('ix_user_gender'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created_ip'), table_name='user')
    op.drop_index(op.f('ix_user_activation_ip'), table_name='user')
    op.drop_table('user')
    # Alembic's autogenerate drops the tables but not the native Postgres enum
    # types they used — drop them explicitly so the migration is fully
    # reversible (otherwise a re-upgrade fails on "type already exists").
    for enum_name in (
        'user_authentication_log_status',
        'user_authentication_log_type',
        'user_authentication_two_factor_status',
        'user_authentication_two_factor_type',
        'user_authentication_status',
        'user_authentication_type',
        'user_theme',
        'user_status',
        'user_type',
        'user_gender',
        'language',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
