# SPDX-FileCopyrightText: 2026 ChallengeMyProject
#
# SPDX-License-Identifier: AGPL-3.0-only

"""create account tables

Revision ID: 20260708190704
Revises: 20260708164326
Create Date: 2026-07-08 21:07:04.798318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


revision: str = '20260708190704'
down_revision: Union[str, None] = '20260708164326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('active', 'disabled', 'blocked', name='account_status'), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=True),
    # `language` type already exists (shared with `user`); reference it without
    # re-creating it.
    sa.Column('language', postgresql.ENUM('fr-FR', 'en-GB', 'es-ES', 'de-DE', 'it-IT', name='language', create_type=False), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('picture_profile', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('time_zone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_created_ip'), 'account', ['created_ip'], unique=False)
    op.create_index(op.f('ix_account_language'), 'account', ['language'], unique=False)
    op.create_index(op.f('ix_account_name'), 'account', ['name'], unique=False)
    op.create_index(op.f('ix_account_status'), 'account', ['status'], unique=False)
    op.create_table('account_user_invitation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('simple', name='account_user_invitation_type'), nullable=False),
    sa.Column('status', sa.Enum('standby', 'accepted', 'refused', 'expired', 'cancelled', name='account_user_invitation_status'), nullable=False),
    sa.Column('status_date', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Enum('owner', 'administrator', 'product_owner', 'qa_manager', 'lead_developer', 'developer', 'data_analyst', 'commentator', name='account_user_role'), nullable=False),
    sa.Column('expire_date', sa.DateTime(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_user_invitation_account_id'), 'account_user_invitation', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_user_invitation_email'), 'account_user_invitation', ['email'], unique=False)
    op.create_index(op.f('ix_account_user_invitation_owner_id'), 'account_user_invitation', ['owner_id'], unique=False)
    op.create_index(op.f('ix_account_user_invitation_role'), 'account_user_invitation', ['role'], unique=False)
    op.create_index(op.f('ix_account_user_invitation_status'), 'account_user_invitation', ['status'], unique=False)
    op.create_index(op.f('ix_account_user_invitation_token'), 'account_user_invitation', ['token'], unique=False)
    op.create_index(op.f('ix_account_user_invitation_type'), 'account_user_invitation', ['type'], unique=False)
    op.create_index('unique_account_email_invitation_standby', 'account_user_invitation', ['account_id', 'email'], unique=True, postgresql_where=sa.text("status = 'standby'"))
    op.create_table('account_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_user_invitation_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('creator', 'guest', name='account_user_type'), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', name='account_user_status'), nullable=False),
    sa.Column('role', sa.Enum('owner', 'administrator', 'product_owner', 'qa_manager', 'lead_developer', 'developer', 'data_analyst', 'commentator', name='account_user_role'), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['account_user_invitation_id'], ['account_user_invitation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_user_account_id'), 'account_user', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_user_account_user_invitation_id'), 'account_user', ['account_user_invitation_id'], unique=False)
    op.create_index(op.f('ix_account_user_role'), 'account_user', ['role'], unique=False)
    op.create_index(op.f('ix_account_user_status'), 'account_user', ['status'], unique=False)
    op.create_index(op.f('ix_account_user_type'), 'account_user', ['type'], unique=False)
    op.create_index(op.f('ix_account_user_user_id'), 'account_user', ['user_id'], unique=False)
    op.create_index('unique_account_user_active', 'account_user', ['account_id', 'user_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_account_user_active', table_name='account_user', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_account_user_user_id'), table_name='account_user')
    op.drop_index(op.f('ix_account_user_type'), table_name='account_user')
    op.drop_index(op.f('ix_account_user_status'), table_name='account_user')
    op.drop_index(op.f('ix_account_user_role'), table_name='account_user')
    op.drop_index(op.f('ix_account_user_account_user_invitation_id'), table_name='account_user')
    op.drop_index(op.f('ix_account_user_account_id'), table_name='account_user')
    op.drop_table('account_user')
    op.drop_index('unique_account_email_invitation_standby', table_name='account_user_invitation', postgresql_where=sa.text("status = 'standby'"))
    op.drop_index(op.f('ix_account_user_invitation_type'), table_name='account_user_invitation')
    op.drop_index(op.f('ix_account_user_invitation_token'), table_name='account_user_invitation')
    op.drop_index(op.f('ix_account_user_invitation_status'), table_name='account_user_invitation')
    op.drop_index(op.f('ix_account_user_invitation_role'), table_name='account_user_invitation')
    op.drop_index(op.f('ix_account_user_invitation_owner_id'), table_name='account_user_invitation')
    op.drop_index(op.f('ix_account_user_invitation_email'), table_name='account_user_invitation')
    op.drop_index(op.f('ix_account_user_invitation_account_id'), table_name='account_user_invitation')
    op.drop_table('account_user_invitation')
    op.drop_index(op.f('ix_account_status'), table_name='account')
    op.drop_index(op.f('ix_account_name'), table_name='account')
    op.drop_index(op.f('ix_account_language'), table_name='account')
    op.drop_index(op.f('ix_account_created_ip'), table_name='account')
    op.drop_table('account')
    # Drop the native Postgres enum types (autogenerate omits them). `language`
    # is intentionally excluded — it is shared with the `user` table.
    for enum_name in (
        'account_user_status',
        'account_user_type',
        'account_user_role',
        'account_user_invitation_status',
        'account_user_invitation_type',
        'account_status',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
