"""create user mcp oauth tables

Revision ID: 20260708164326
Revises: 20260708124621
Create Date: 2026-07-08 18:43:26.691555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '20260708164326'
down_revision: Union[str, None] = '20260708124621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_mcp_client',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_secret_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('client_secret_expires_at', sa.DateTime(), nullable=True),
    sa.Column('redirect_uris', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('grant_types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('response_types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('token_endpoint_auth_method', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('software_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('software_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_mcp_authorization_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('flow_type', sa.Enum('device', 'authorization_code', name='mcp_authorization_flow_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'denied', 'expired', 'consumed', name='mcp_authorization_request_status'), nullable=False),
    sa.Column('requested_scope', sa.Enum('read', 'write', name='mcp_grant_scope'), nullable=False),
    sa.Column('approved_scope', sa.Enum('read', 'write', name='mcp_grant_scope'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('device_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('polling_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('authorization_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('redirect_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('code_challenge', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('code_challenge_method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['user_mcp_client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_mcp_authorization_request_authorization_code'), 'user_mcp_authorization_request', ['authorization_code'], unique=True)
    op.create_index(op.f('ix_user_mcp_authorization_request_client_id'), 'user_mcp_authorization_request', ['client_id'], unique=False)
    op.create_index(op.f('ix_user_mcp_authorization_request_device_code'), 'user_mcp_authorization_request', ['device_code'], unique=True)
    op.create_index(op.f('ix_user_mcp_authorization_request_expires_at'), 'user_mcp_authorization_request', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_mcp_authorization_request_flow_type'), 'user_mcp_authorization_request', ['flow_type'], unique=False)
    op.create_index(op.f('ix_user_mcp_authorization_request_requested_scope'), 'user_mcp_authorization_request', ['requested_scope'], unique=False)
    op.create_index(op.f('ix_user_mcp_authorization_request_status'), 'user_mcp_authorization_request', ['status'], unique=False)
    op.create_index(op.f('ix_user_mcp_authorization_request_user_code'), 'user_mcp_authorization_request', ['user_code'], unique=True)
    op.create_index(op.f('ix_user_mcp_authorization_request_user_id'), 'user_mcp_authorization_request', ['user_id'], unique=False)
    op.create_table('user_mcp_grant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.Enum('read', 'write', name='mcp_grant_scope'), nullable=False),
    sa.Column('status', sa.Enum('active', 'revoked', name='mcp_grant_status'), nullable=False),
    sa.Column('grant_control', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['user_mcp_client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_mcp_grant_client_id'), 'user_mcp_grant', ['client_id'], unique=False)
    op.create_index(op.f('ix_user_mcp_grant_scope'), 'user_mcp_grant', ['scope'], unique=False)
    op.create_index(op.f('ix_user_mcp_grant_status'), 'user_mcp_grant', ['status'], unique=False)
    op.create_index(op.f('ix_user_mcp_grant_user_id'), 'user_mcp_grant', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mcp_grant_user_id'), table_name='user_mcp_grant')
    op.drop_index(op.f('ix_user_mcp_grant_status'), table_name='user_mcp_grant')
    op.drop_index(op.f('ix_user_mcp_grant_scope'), table_name='user_mcp_grant')
    op.drop_index(op.f('ix_user_mcp_grant_client_id'), table_name='user_mcp_grant')
    op.drop_table('user_mcp_grant')
    op.drop_index(op.f('ix_user_mcp_authorization_request_user_id'), table_name='user_mcp_authorization_request')
    op.drop_index(op.f('ix_user_mcp_authorization_request_user_code'), table_name='user_mcp_authorization_request')
    op.drop_index(op.f('ix_user_mcp_authorization_request_status'), table_name='user_mcp_authorization_request')
    op.drop_index(op.f('ix_user_mcp_authorization_request_requested_scope'), table_name='user_mcp_authorization_request')
    op.drop_index(op.f('ix_user_mcp_authorization_request_flow_type'), table_name='user_mcp_authorization_request')
    op.drop_index(op.f('ix_user_mcp_authorization_request_expires_at'), table_name='user_mcp_authorization_request')
    op.drop_index(op.f('ix_user_mcp_authorization_request_device_code'), table_name='user_mcp_authorization_request')
    op.drop_index(op.f('ix_user_mcp_authorization_request_client_id'), table_name='user_mcp_authorization_request')
    op.drop_index(op.f('ix_user_mcp_authorization_request_authorization_code'), table_name='user_mcp_authorization_request')
    op.drop_table('user_mcp_authorization_request')
    op.drop_table('user_mcp_client')
    # Drop the native Postgres enum types (autogenerate omits them) so the
    # migration is fully reversible.
    for enum_name in (
        'mcp_grant_status',
        'mcp_authorization_request_status',
        'mcp_authorization_flow_type',
        'mcp_grant_scope',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
