# SPDX-FileCopyrightText: 2026 ChallengeMyProject
#
# SPDX-License-Identifier: AGPL-3.0-only

"""database table index and constraint

Revision ID: 20260719202816
Revises: 20260719201905
Create Date: 2026-07-19 22:28:16.193075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '20260719202816'
down_revision: Union[str, None] = '20260719201905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_table_constraint',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('database_table_id', sa.Uuid(), nullable=False),
    sa.Column('foreign_key_database_table_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('primary_key', 'unique', 'foreign_key', 'check', 'not_null', name='constraint_type'), nullable=False),
    sa.Column('column_ids', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('check_expression', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('foreign_key_column_ids', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('on_delete', sa.Enum('no_action', 'restrict', 'cascade', 'set_null', 'set_default', name='referential_action'), nullable=True),
    sa.Column('on_update', sa.Enum('no_action', 'restrict', 'cascade', 'set_null', 'set_default', name='referential_action'), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['database_table_id'], ['database_table.id'], ),
    sa.ForeignKeyConstraint(['foreign_key_database_table_id'], ['database_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_table_constraint_account_id'), 'database_table_constraint', ['account_id'], unique=False)
    op.create_index(op.f('ix_database_table_constraint_database_table_id'), 'database_table_constraint', ['database_table_id'], unique=False)
    op.create_index(op.f('ix_database_table_constraint_foreign_key_database_table_id'), 'database_table_constraint', ['foreign_key_database_table_id'], unique=False)
    op.create_index(op.f('ix_database_table_constraint_name'), 'database_table_constraint', ['name'], unique=False)
    op.create_index(op.f('ix_database_table_constraint_rank'), 'database_table_constraint', ['rank'], unique=False)
    op.create_index(op.f('ix_database_table_constraint_type'), 'database_table_constraint', ['type'], unique=False)
    op.create_table('database_table_index',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('database_table_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('btree', 'hash', 'gin', 'gist', 'brin', name='index_type'), nullable=False),
    sa.Column('unique', sa.Boolean(), nullable=False),
    sa.Column('column_ids', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('where_clause', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['database_table_id'], ['database_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_table_index_account_id'), 'database_table_index', ['account_id'], unique=False)
    op.create_index(op.f('ix_database_table_index_database_table_id'), 'database_table_index', ['database_table_id'], unique=False)
    op.create_index(op.f('ix_database_table_index_name'), 'database_table_index', ['name'], unique=False)
    op.create_index(op.f('ix_database_table_index_rank'), 'database_table_index', ['rank'], unique=False)
    op.create_index(op.f('ix_database_table_index_type'), 'database_table_index', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_database_table_index_type'), table_name='database_table_index')
    op.drop_index(op.f('ix_database_table_index_rank'), table_name='database_table_index')
    op.drop_index(op.f('ix_database_table_index_name'), table_name='database_table_index')
    op.drop_index(op.f('ix_database_table_index_database_table_id'), table_name='database_table_index')
    op.drop_index(op.f('ix_database_table_index_account_id'), table_name='database_table_index')
    op.drop_table('database_table_index')
    op.drop_index(op.f('ix_database_table_constraint_type'), table_name='database_table_constraint')
    op.drop_index(op.f('ix_database_table_constraint_rank'), table_name='database_table_constraint')
    op.drop_index(op.f('ix_database_table_constraint_name'), table_name='database_table_constraint')
    op.drop_index(op.f('ix_database_table_constraint_foreign_key_database_table_id'), table_name='database_table_constraint')
    op.drop_index(op.f('ix_database_table_constraint_database_table_id'), table_name='database_table_constraint')
    op.drop_index(op.f('ix_database_table_constraint_account_id'), table_name='database_table_constraint')
    op.drop_table('database_table_constraint')
    # ### end Alembic commands ###
